"use strict";

const QuillConfig = {
    element: null,
    fonts: {
        proportional: "'Open Sans', Arial, Helvetica, sans-serif",
        monospace: "Consolas, 'Courier New', Courier, monospace",
    },
    colors: {
        background: new QuillColor(40, 40, 40),
        panel_title_bar: new QuillColor(20, 20, 20),
        panel_content: new QuillColor(30, 30, 30),
        menu: new QuillColor(50, 50, 50),
        item_background: new QuillColor(50, 50, 50),
        item_hover: new QuillColor(70, 70, 70),
        line_heavy: new QuillColor(255, 255, 255, 0.1),
        line_light: new QuillColor(255, 255, 255, 0.1),
        text: new QuillColor(255, 255, 255, 0.5),
        input: new QuillColor(0, 192, 255, 1),
        scrollbar_thumb: new QuillColor(30, 30, 30),
        scrollbar_track: new QuillColor(50, 50, 50),
        panel_border: new QuillColor(72, 61, 139),
    },
    sizes: {
        font_size: 14,
        panel_padding: 5,
        panel_gap: 5,
        panel_border: 0,
        panel_border_radius: 5,
        panel_shadow: 8,
        panel_resizer: 5,
        menu_padding: 2,
        menu_gap: 2,
        menu_border: 0,
        menu_border_radius: 5,
        menu_shadow: 8,
        item_padding: 1,
        item_gap: 1,
        item_border_radius: 3,
        line_heavy: 1,
        line_light: 1,
    },
};
