"use strict";

const QuillConfig = {
    element: null,
    fonts: {
        proportional: "'Open Sans', Arial, Helvetica, sans-serif",
        monospace: "Consolas, 'Courier New', Courier, monospace",
    },
    colors: {
        background: new QuillColor(40, 40, 40),
        panel_title_bar: new QuillColor(20, 20, 20),
        panel_content: new QuillColor(30, 30, 30),
        menu: new QuillColor(50, 50, 50),
        item_background: new QuillColor(50, 50, 50),
        item_hover: new QuillColor(70, 70, 70),
        input_border: new QuillColor(0, 138, 110),
        line: new QuillColor(70, 70, 70),
        text: new QuillColor(150, 150, 150),
        item_hover_text: new QuillColor(220, 220, 220),
        input: new QuillColor(0, 190, 255),
        input_hovered_text: new QuillColor(128, 223, 255),
        scrollbar_thumb: new QuillColor(30, 30, 30),
        scrollbar_track: new QuillColor(50, 50, 50),
        panel_border: new QuillColor(72, 61, 139),
    },
    sizes: {
        font_size: 20,
        panel_padding: 2,
        panel_gap: 2,
        panel_border: 2,
        panel_border_radius: 0,
        panel_shadow: 0,
        menu_padding: 0,
        menu_gap: 2,
        menu_border: 2,
        menu_border_radius: 0,
        menu_shadow: 0,
        item_padding: 0,
        item_gap: 2,
        item_inner_gap: 2,
        item_border_radius: 0,
        input_border: 2,
        line: 2,
        indentation: 20,
    },
    flags: {
        labels_left: false,
        justify_labels: false,
    },
};
